source 'https://github.com/CocoaPods/Specs.git'

target 'LMArrayChangeSets' do
  pod "LMArrayChangeSets", :path => "../"
end

target 'Tests' do
  pod "LMArrayChangeSets", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
